### ISSUE TITLE
Gaussian priors and covariance structure

### ISSUE THREAD

**Issue by joshuawchen** [hippylib/hippylib#12]
I wonder if others may find this useful, as I would. An interface for making covariance operator creation easy to understand, along with an example in hippylib solely highlighting the covariance, and the effect of the scales of the parameters on the correlation length. Plotting a column of the covariance as an image would provide intuition of the correlation length. This may simply be an example, rather than a change of interface, but I’m not sure.

**Comment by joshuawchen** [comment]
Yes I like the suggestion above, one thought is to simply make it a _private_method, and provide an example usage of if in the example file. Visualizations will be very useful to people who want to tweak covariances often, and this private method would probably be used often by people in jupyter notebooks for example, as they come up with examples to use for papers.

**Comment by uvilla** [comment]
Why *private*? If you make it private it means it should **not** be called by the user...

**Comment by joshuawchen** [comment]
The other approach is to provide a warning to the logger if mpi has more than one rank. Is Logging implemented at any level in hippylib now? If not, I could raise an issue for this as well. I’ve recently become a fan of the python logger (import logging)

**Comment by uvilla** [comment]
Rescaling the vector is all what you need to ensure correctness. It is not pretty but it does the job.
