### ISSUE TITLE
Feature request- introducing Besov measure priors

### ISSUE THREAD

**Issue by joshuawchen** [hippylib/hippylib#13]
This may be of interest to many users. I am also personally interested in implementation of this, possibly myself.

**Comment by uvilla** [comment]
Hi Josh,

The main issues here is that practical implementation of Besov priors requires a parametrization of the sought-after parameter using nonlocal shape functions (e.g. wavelets). This means that one can not rely on FEniCS for such parametrizations.

**Comment by joshuawchen** [comment]
My thought was along the lines of anisotropic Laplace like besov priors, along the lines of Bamdad’s paper here https://arxiv.org/pdf/1604.02575.pdf, which I believe can be implemented without wavelets? I’ve implemented some similar finite dimensional toy examples of anisotropic Laplace priors successfully (not for PDEs).

**Comment by uvilla** [comment]
Are you referring to formula (1.9) in Bamdad's paper? There he uses a Fourier basis, that is global.
This means that operators representing mixed derivatives involving the parameters will be dense matrices.

I don't think we can support large-scale problems with Besov Priors. At most, we could add a `LaplaceRealPrior` similar to the `GaussianRealPrior` in this [PR](https://github.com/hippylib/hippylib/pull/7/files).

**Comment by joshuawchen** [comment]
Hm, I'll have to think a bit more. I was under the impression that one could generate Laplace like (p = 1), Besov measure samples in infinite dimensions using this: 

\mu + \sqrt{Z}\Lambda^{½}X, where X is a `infinite dimensional` standard Gaussian, i.e. white noise, \Lambda is the Covariance, Z is a realization of a scalar exponential random variable, and \mu is a mean. 

If this is correct, then since hippylib cleverly calculates Lambda^{½}, I thought Besov measure with p = 1 is possible for us. Maybe this is naive.

Regardless, I like the idea at least of a LaplaceRealPrior, definitely.

**Comment by joshuawchen** [comment]
Seems maybe what I’m saying is true for a very particular Besov measure with p=1, and s = ½ maybe? 

Regardless, if I am indeed correct, which is suspect, well- in that case we have a scalable way to draw from a particular multidimensional  Laplace like besov prior. This is pretty attractive to me..

**Comment by uvilla** [comment]
This is a rather complex feature to implement. We should postpone the discussion until a research project requires it and a developer want to champion it
