### ISSUE TITLE
Logging/Prints/Exceptions

### ISSUE THREAD

**Issue by joshuawchen** [hippylib/hippylib#15]
1) Providing logging for the hippylib package

2) moving all prints to the logger

3)  creating hIPPYlib particular exceptions for places where exceptions can occur. This is done by inheriting from Exception class.

**Comment by uvilla** [comment]
I’m not against using logging in principle, but I’m afraid it may scare away other developers to contribute to the project. We would have to document very well and clearly the use of logging in the developer guidelines. Also we should find ways to enforce the use of logging/exception before merging any pull request.

**Comment by joshuawchen** [comment]
I’m ok with trying to get this started.

**Comment by eldarkh** [comment]
Logging and customized exception would be nice to have, I agree
