### ISSUE TITLE
Abstract methods 

### ISSUE THREAD

**Issue by joshuawchen** [hippylib/hippylib#18]
Easier than raising lots of NotImplementedError messages, one could consider using the @abstractmethod decorator, which is nicely readable, intuitive, and compact. https://docs.python.org/3/library/abc.html

**Comment by uvilla** [comment]
Agree.

**Comment by joshuawchen** [comment]
I can easily do this some afternoon, and create a pull request. If won’t effect any user.

**Comment by eldarkh** [comment]
Does it really add anything though? You will have to have almost the same amount of code writing the ABC class, and, in my opinion, it's use is very subtle - mainly it gives a nice `__subclasshook__` approach but are we going to ever benefit from that?

**Comment by joshuawchen** [comment]
You actually only need to use the decorator, the rest is not necessary. We don’t need inheritance from an abc class

**Comment by joshuawchen** [comment]
Yes on top of each abstract method. It’s still simpler, I would argue, and leads to not having to code a bunch of print statements each time. Since we sort of impose an interface, and we do use inheritances it makes sense to me to offer these abstract methods in the base class. People are free to create classes that don’t even inherit from the base class (but with the same interface) which would still work, but when looking at base classes for information to code, it’s super simple to just read the abstract methods, as well as the docstrinfs for them to be guided on how to create your own.
