### ISSUE TITLE
Privatize variables that aren’t part of the public interface

### ISSUE THREAD

**Issue by joshuawchen** [hippylib/hippylib#19]
One could privatize much of the variables stored in classes in hippylib, and leave variables that are commonly accessed on the outside, for example, noise_variance, as a @property, with a getter and setter function. This is not a large undertaking logically, but definitely could lead to mistakes if one is not careful to replace all instances of variables.

Benefits of this are more clarity to the user when using help(class_instance), etc.

Also, lots of these variables should not be changed on the outside. To do so would violate the interface, and break things.

**Comment by eldarkh** [comment]
I can work on this, this is a good change to overall readability

**Comment by joshuawchen** [comment]
Ok, I can take a look at the pull request after its written. I had a few properties in mind that could be decorated with @property and have .setters.

**Comment by siddhantwahal** [comment]
@joshuawchen I just implemented exactly this (noise_variance with setters) in our Exxon branch!

**Comment by joshuawchen** [comment]
@siddhantwahal link to the branch? can't find it

**Comment by siddhantwahal** [comment]
> @siddhantwahal link to the branch? can't find it

Emailed the link to you.

**Comment by uvilla** [comment]
It is a nice idea to use `@property` decorators and *privatize* variables.
Again, though we should move slowly. One class (or group of classes at a time) so that it is easier to make sure we are not introducing bugs.
