### ISSUE TITLE
Docker image for hippylib

### ISSUE THREAD

**Issue by quang-ha** [hippylib/hippylib#2]
Consider FEniCS has now distributed their package via docker images, wouldn't it be convenience if we also have one for hIPPYlib?

**Comment by hippylib-admin** [comment]
Hi Quang-Ha,

We did some experiments using Docker+Hippylib, but we are not fully satisfied yet with the workflow.
We are still learning Docker, and we will definitely provide a Dockerfile for hippylib sometimes in the near future.

For now, you could just try the following commands:

1) clone on your local hard-drive the hippylib repository or download the latest release.
2) Change directory to the `hippylib` folder
3) Type the command:

```sh
docker run --name hippylib-notebook -w /home/fenics/hippylib -v $(pwd):/home/fenics/hippylib -d -p 127.0.0.1:8888:8888 quay.io/fenicsproject/stable:1.6.0 'jupyter-notebook --ip=0.0.0.0'
```

**Note**: this syntax only works if you are using Docker in Linux, Docker for Mac, or Docker for Windows. The syntax will need slight modifications if you are using Docker Toolbox.

4) Open your browser at `http://localhost:8888`

5) You can now run the ipython notebooks inside `hippylib/tutorial` or you can open a new shell and run the python script inside `hippylib/applications/*`.

6) Remember to shut-down the container when you are done:
```
docker stop hippylib-notebook
```

7) To restart the container simply type
```
docker stop hippylib-notebook
```
Then repeat steps 4 to 7.

Best,

Umberto

**Comment by uvilla** [comment]
We now have a `Docker` container with the latest hIPPYlib release. See [https://hippylib.github.io/documentation/](https://hippylib.github.io/documentation/)
