### ISSUE TITLE
Emulators framework for hippylib

### ISSUE THREAD

**Issue by eldarkh** [hippylib/hippylib#21]
@AIlona and me were discussing the ability of having surrogate models within hippylib/fenics framework. It is somewhat motivated by Omar mentioning one of his students work on using neural nets as proxies for the forward model, also it seems to be popular to do GP approach to the same thing. 

This could be approached by having an Emulator class that has Problem object as attribute, and does the fitting/training of the specific model at initialization. The initialization would rely on specific implementation that can be provided by user, and we can also provide a couple of standard things as part of the library (some GPs and 2-3 kernels for it, neural nets etc)

Any thoughts would be greatly apprectiated

**Comment by joshuawchen** [comment]
This is interesting. However, to do this, I think we would need a richer interface for realizations from priors. Since there would be a mapping between realizations and their mapping through the emmulator/surrogate model, and the surrogate model may not be the same function for each realization. Just some thoughts!

**Comment by uvilla** [comment]
I'm also in favor of adding new conceptual features to `hIPPYlib`, and I definitely support adding Gaussian Processes or other *emulators*.

Depending on the complexity of the task, this could be
- a submodule in `hIPPYlib`
- a separate project that depends on `hIPPYlib`
- a separate project that `hIPPYlib` optionally depends on

**Comment by joshuawchen** [comment]
One thing that may be nice to have in general is a `Kernel` class. This would be used for some MCMC methods which current use kernels, as well as for GP's. The other area it would be useful is code we currently have in the group for Stein methods, which involve Kernels. In general, it seems the notion of a Kernel is very useful for lots of things that we will be prototyping related to bayesian inverse problems.
