### ISSUE TITLE
Correlated misfits/Non iid Gaussian noise models

### ISSUE THREAD

**Issue by joshuawchen** [hippylib/hippylib#28]
It would be nice to build availability for non iid Gaussian noise models for the misfit/likelihood term. Correlated noise, particularly when the data are pointwise observations, based on correlation length, for example, could be interesting, or even just a user provided covariance function.

Also, providing nonGaussian noise models, and corresponding misfits would be interesting. 

For example, Laplace noise, would lead essentially to an L1-like misfit, as with this presentation below. Sometimes this type of noise may be physically relevant too. It’s also numerically attractive to solve these kinds of problems (sparsity is in vogue!)

https://www.uni-due.de/imperia/md/content/mathematik/agclason/lanoise_pres5.pdf

**Comment by uvilla** [comment]
hIPPYlib development is driven by current projects needs. A contribution to this feature (if well tested and general enough) is welcomed!
