### ISSUE TITLE
`GaussianRealPrior.R` has no method `inner`

### ISSUE THREAD

**Issue by siddhantwahal** [hippylib/hippylib#29]
The regularization operator in `prior.GaussianRealPrior` is a `dl.Matrix`, with no classmethod `inner`. The only place where `R.inner` is used in the rest of the library is `mcmc/kernels.py`, like so:

```
def delta(self,sample):
        dm_nu = sample.m - self.nu.mean
        dm_pr = sample.m - self.prior.mean
        return sample.cost + .5*self.prior.R.inner(dm_pr, dm_pr) - .5*self.nu.Hlr.inner(dm_nu, dm_nu)
```

Fortunately, this has a simple fix:

```
def delta(self,sample):
        dm_nu = sample.m - self.nu.mean
        return sample.cost + self.prior.cost(sample.m) - .5*self.nu.Hlr.inner(dm_nu, dm_nu)
```

The other option is to emulate `GaussianRealPrior.R` via a new class, and then define an `inner` method.

**Comment by uvilla** [comment]
Why not binding a free function `inner` to the object `R` using `types.MethodType`?

See here,
https://stackoverflow.com/questions/972/adding-a-method-to-an-existing-object-instance

Something on the lines of 
```
def inner(R,x,y):
    return x.inner(R*y)

R.inner = types.MethodType(inner, R)
```

**Comment by uvilla** [comment]
The other option is to solve the problem as in your PR #30, and to deprecate `inner` for the ` BilaplacianR`
