### ISSUE TITLE
Bayesian quantification of parameter uncertainty

### ISSUE THREAD

**Issue by cepez** [hippylib/hippylib#5]
Hi,

First, thank you for this nice library, it's being quite helpful for my work!

I am starting now to use hippylib at the same time I am learning how to estimate uncertainty in statistical inverse problems using Bayesian inference. As you can imagine, I have a lot of  questions that I hope you can answer at your convenience:

We are dealing with a system with the following characteristics. Attached are also the questions regarding different issues on the set up process:

(1) We are considering a Gaussian prior. How should be be set up the prior covariance matrix in general? Could it be given always by the discretization of the inverse of differential operator A that you use in the "Bayesian quantification of parameter uncertainty" example of your tutorial ?
 
(2) A Noise model is white-noise Gaussian is assumed. How is the covariance matrix in this case?

(3) In our case the forward model mapping parameters to the observables is not a linear operator. With this condition is still possible to make the Gaussian approximation of the posterior? (like the one included in the "Bayesian quantification of parameter uncertainty" example).

Thanks for your help!

**Comment by uvilla** [comment]
Hi Cepez,

Thank you for your interest in hippylib.

(1) The choice of the prior covariance is a modeling choice which is problem dependent. In hIPPYlib, we model the prior covariance as the inverse of a differential operator as described in:

http://epubs.siam.org/doi/10.1137/12089586X
and
https://doi.org/10.1017/S0962492910000061

(2) For pointwise observation we assume i.i.d. Gaussian noise with zero mean and fixed variance.
Therefore the noise covariance is a scalar multiple of the identity. It is trivial to implement different noise covariance operators.

(3) For a linear parameter to observable map the posterior is indeed Gaussian (i.e. the Laplace approximation is the posterior distribution). In the general case of nonlinear parameter to observable map the Laplace approximation may or may not be an accurate approximation to the posterior. This is problem dependent, but in general one should expect that the true posterior distribution has heavier tails than the Laplace approximation.
Also note that the quality of the approximation does not depend on whether the forward problem is linear or nonlinear, but only on how much nonlinear is the parameter to observable map. For example, in the poisson problem the parameter (i.e. log permeability field) to observable (pressure at given location) is non linear, although the forward problem (darcy flow) is linear in the state variable.

**Comment by uvilla** [comment]
Dear Cepez,

I hope that the above answers is helpful.

I am now going to close this issue, since the purpose of the `issue` tool is to track bugs in the code.

**Comment by cepez** [comment]
Thank you so much for your answers and sorry for  spamming
