### ISSUE TITLE
Adjoint solver in PDEProblem.py

### ISSUE THREAD

**Issue by kthj** [hippylib/hippylib#50]
I think the boundary conditions should be also applied to the right-hand side of the adjoint problem in PDEProblem.py.

The code should read (from what I corrected)

```python
    def solveAdj(self, adj, x, adj_rhs):
        """ Solve the linear adjoint problem: 
            Given :math:`m, u`; find :math:`p` such that
            
                .. math:: \\delta_u F(u, m, p;\\hat{u}) = 0, \\quad \\forall \\hat{u}.
        """
        if self.solver is None:
            self.solver = self._createLUSolver()
            
        u = vector2Function(x[STATE], self.Vh[STATE])
        m = vector2Function(x[PARAMETER], self.Vh[PARAMETER])
        p = dl.Function(self.Vh[ADJOINT])
        du = dl.TestFunction(self.Vh[STATE])
        dp = dl.TrialFunction(self.Vh[ADJOINT])
        varf = self.varf_handler(u, m, p)
        adj_form = dl.derivative( dl.derivative(varf, u, du), p, dp )
        Aadj, dummy = dl.assemble_system(adj_form, dl.inner(u,du)*dl.dx, self.bc0)
        [bc.apply(adj_rhs) for bc in self.bc0]
        self.solver.set_operator(Aadj)
        self.solver.solve(adj, adj_rhs)
```
where `[bc.apply(adj_rhs) for bc in self.bc0]` is inserted.

I have run a simple 1D problem and got an accurate value with this correction (for example, the gradient of the objective function with respect to the parameter. Without this correction, the Newton CG stops with an error message "Maximum number of backtracking reached", because the gradient is inaccurately computed (but the error is small so in some cases, it successfully runs) ).

**Comment by uvilla** [comment]
In `hIPPYlib` the `misfit` must handle Dirichlet condition for the state variable.

That is `misfit.grad(STATE, x)` needs to ensure the gradient w.r.t. the state is 0 on Dirichlet nodes.

**Comment by kthj** [comment]
Thank you for your reply.

You mean that `misfit.grad` needs to be corrected?

The reason why I edited `pde.solveAdj` is that we apply the adjoint boundary condition in the sense that we do it to the whole linear system `Ax = b`, not just to the matrix 'A'.

**Comment by uvilla** [comment]
What type of misfit are you using?

`ContinuousStateObservation` already takes care of ensuring the r.h.s. for the adjoint problem is zero on the dirichlet dofs.

When using `PointwiseStateObservation`, is up to the user make sure they don't put an observation point on a Dirichlet boundary.

**Comment by kthj** [comment]
I got it.

It is because of using `PointwiseStateObservation`.

Thank you!
