### ISSUE TITLE
Use of hIPPYlib to do parameter estimation on ODE systems?

### ISSUE THREAD

**Issue by teopb** [hippylib/hippylib#52]
I hope this is a reasonable place to post this question but it is where all the 'contact us' links pointed. I am interested in using hIPPYlib to explore some MCMC-type parameter estimation on some relatively simple ODE systems (lorenz 63). As I am also interested in using hIPPYlib for PDE advection problems in the future I thought it would be good to dip my toes in now with this simple problem. But I haven't seen any examples of something of this sort. Would it be possible to use hIPPYlib for this purpose? Thank you!

**Comment by joshuawchen** [comment]
hIPPYlib is bit for PDE parameter estimation and Bayesian inference. Email me at joshuawchen@utexas.edu, if you want any particular suggestions concerning Lorenz 63
