### ISSUE TITLE
PETSc was configured with one MPICH mpi.h version but ...

### ISSUE THREAD

**Issue by truonghuynhmuni** [hippylib/hippylib#54]
I tried running example **1_FEniCS101** and encountered the following problem:
`Moving new file over differing existing file:
src: /Users/tanggo/Desktop/hippylib/tutorial/jitfailure-dolfin_cpp_module_a52fd91d2eca0c2f97936aa964f95a82/recompile.sh.f2fb22167bc1494d90f9010c8fdb2d1b
dst: /Users/tanggo/Desktop/hippylib/tutorial/jitfailure-dolfin_cpp_module_a52fd91d2eca0c2f97936aa964f95a82/recompile.sh
backup: /Users/tanggo/Desktop/hippylib/tutorial/jitfailure-dolfin_cpp_module_a52fd91d2eca0c2f97936aa964f95a82/recompile.sh.old
Moving new file over differing existing file:
src: /Users/tanggo/Desktop/hippylib/tutorial/jitfailure-dolfin_cpp_module_a52fd91d2eca0c2f97936aa964f95a82/error.log.24648fd9f3c143328dea7cc91fcf2a18
dst: /Users/tanggo/Desktop/hippylib/tutorial/jitfailure-dolfin_cpp_module_a52fd91d2eca0c2f97936aa964f95a82/error.log
backup: /Users/tanggo/Desktop/hippylib/tutorial/jitfailure-dolfin_cpp_module_a52fd91d2eca0c2f97936aa964f95a82/error.log.old
Backup file exists, overwriting.
------------------- Start compiler output ------------------------
In file included from /var/folders/cw/5_193fln67g7r3dqbhcwjr8w0000gn/T/tmpxtkdbu5_/dolfin_cpp_module_a52fd91d2eca0c2f97936aa964f95a82.cpp:18:
In file included from /Users/tanggo/opt/anaconda3/envs/fenics2/include/dolfin/la/PETScVector.h:37:
/Users/tanggo/opt/anaconda3/envs/fenics2/include/petscsys.h:163:6: error: "PETSc was configured with one MPICH mpi.h version but now appears to be compiling using a different MPICH mpi.h version"
error "PETSc was configured with one MPICH mpi.h version but now appears to be compiling using a different MPICH mpi.h version"
     ^
1 error generated.

-------------------  End compiler output  ------------------------
Compilation failed! Sources, command, and errors have been written to: /Users/tanggo/Desktop/hippylib/tutorial/jitfailure-dolfin_cpp_module_a52fd91d2eca0c2f97936aa964f95a82`

I would like to know how to solve it.

**Comment by uvilla** [comment]
This issue is related to the `FEniCS` conda packages not `hIPPYlib`.

Please see the FEniCS's Discourse board for a proposed walkaround:

https://fenicsproject.discourse.group/t/problem-with-conda-install/5244
