### ISSUE TITLE
Clarification on why rejected samples are not excluded from moment estimation

### ISSUE THREAD

**Issue by thartland** [hippylib/hippylib#78]
The proposal kernels each contain a `sample` member function (e.g., [here](https://github.com/hippylib/hippylib/blob/master/hippylib/mcmc/kernels.py#L46-L56)), which return `1` when the sample point is to be accepted and `0` otherwise. Given that, I'm confused why `chain.py` does not exclude qoi evaluations `q` when `kernel.sample` returns `0` from `sum_q` and `sum_q2` [here](https://github.com/hippylib/hippylib/blob/master/hippylib/mcmc/chain.py#L99-L109), which I assume are used to estimate the first and second moments of the push through distribution of `q=qoi(m)` given a distribution on `m`. Clarification on this matter would be appreciated.

**Comment by uvilla** [comment]
This is the MCMC algorithm.
At step `{n+1}` we set `m_{n+1} = proposed_m` if accepted and`m_{n+1} = m_{n}` if rejected.

Note that if the proposed point is rejected, we simply weight more the current point when computing statistics.

**Comment by thartland** [comment]
Thanks @uvilla, this was due to a misunderstanding on my end.
